# Generated by Django 4.2.4 on 2023-08-08 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_rename_created_date_product_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category_id",
            new_name="category",
        ),
    ]
