# Generated by Django 4.2.4 on 2023-08-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_rename_category_id_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="product.tag"),
        ),
    ]
